### ISSUE TITLE
Requesting for DataSet

### ISSUE THREAD

**Issue by Ganesh9100** [harsha-desaraju/Optical-Character-Recognition-OCR-for-Telugu#3]
Hi Harsha Desaraju, Great Work. Out of curiosity could you please attach the data set that is used for training this model. I would like to see and explore the dataset.

**Comment by harsha-desaraju** [comment]
Unfortunately, the authors of the paper have shut down the website where the dataset was available. You can write to them requesting the dataset. The paper is mentioned in the readme.

**Comment by Ganesh9100** [comment]
Okay, Thanks for your valuable comment.

**Comment by Siddharth-Shrivastava7** [comment]
Hi @Ganesh9100 have you got the dataset from the authors?

**Comment by Ganesh9100** [comment]
No yet

**Comment by Siddharth-Shrivastava7** [comment]
Ohh I see, Thanks for the quick response.

**Comment by Manohar-DLMR** [comment]
Hi @Ganesh9100 & @Siddharth-Shrivastava7,

Did any of you manage to get the dataset?

**Comment by Ganesh9100** [comment]
No not yet.

**Comment by Manohar-DLMR** [comment]
Okay, Thank you for your quick response.

**Comment by Siddharth-Shrivastava7** [comment]
No, I too didn't get
